{{- if .Values.serviceAccount.helloGin.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tamuraApp.helloGin.serviceAccountName" . }}
  labels:
    {{- include "tamuraApp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.helloGin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
