apiVersion: v1
kind: Service
metadata:
  name: {{ include "tamuraApp.helloMongo.fullname" . }}
  labels:
    {{- include "tamuraApp.helloMongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helloMongo.service.type }}
  ports:
    - port: {{ .Values.helloMongo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tamuraApp.helloMongo.selectorLabels" . | nindent 4 }}
