apiVersion: v1
kind: Service
metadata:
  name: {{ include "tamuraApp.helloGin.fullname" . }}
  labels:
    {{- include "tamuraApp.helloGin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helloGin.service.type }}
  ports:
    - port: {{ .Values.helloGin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tamuraApp.helloGin.selectorLabels" . | nindent 4 }}
