apiVersion: v1
kind: Service
metadata:
  name: {{ include "tamuraApp.mongodb.fullname" . }}
  labels:
    {{- include "tamuraApp.mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "tamuraApp.mongodb.selectorLabels" . | nindent 4 }}
